accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.log_in, name='login'),
    path('logout/', LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('loginmain/', views.loginmain, name='loginmain'),
]

main/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index ,name='first'),
    path('loginmain/', views.loginmain ,name='loginmain'),
]

myku/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    #path('accounts/', include('django.contrib.auth.urls')),
]

accounts/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.db import models
from django.contrib.auth.models import User, UserManager
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import AbstractUser
"""
class Profile(models.Model):
    GRADES = (
        ('freshman', '1학년'),
        ('sophomore', '2학년'),
        ('junior', '3학년'),
        ('senior', '4학년'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nickname = models.TextField(max_length=10, verbose_name='닉네임')
    major = models.TextField(max_length=20, null=True, verbose_name='학과')
    #major_one = models.TextField(max_length=20, null=True)
    #major_two = models.TextField(max_length=20, null=True)
    grade = models.PositiveSmallIntegerField(null=True, choices=GRADES, verbose_name='학년')
    REQUIRED_FIELDS = ('user',)
    USERNAME_FIELD = User.username
"""


class Profile(AbstractUser):
    GRADES = (
        ('1학년', '1학년'),
        ('2학년', '2학년'),
        ('3학년', '3학년'),
        ('4학년', '4학년'),
    )
    email = models.EmailField(verbose_name="email", max_length=255, unique=True)
    username = models.CharField(max_length=30)
    nickname = models.TextField(max_length=10)
    major = models.TextField(max_length=20, null=True)
    grade = models.CharField(max_length=20, null=True, choices=GRADES)
    USERNAME_FIELD = 'email'
    objects = UserManager()
    REQUIRED_FIELDS = []

    def __str__(self):
        return "<%d %s>" % (self.pk, self.email)

class UserManager(BaseUserManager):
    def _create_user(self, email, username, password,**extra_fields):
        if not email:
            raise ValueError('The given email mist be set')
        email = self.normalize_email(email)
        username = self.model.normalize_username(username)
        user = self.model(email=email, username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, username='', password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, username, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff = True')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser = True')

        return self._create_user(email, password, **extra_fields)

"""
class Profile(models.Model):
    GRADES = (
        ('freshman', '1학년'),
        ('sophomore', '2학년'),
        ('junior', '3학년'),
        ('senior', '4학년'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nickname = models.TextField(max_length=10)
    major = models.TextField(max_length=20, null=True)
    #major_one = models.TextField(max_length=20, null=True)
    #major_two = models.TextField(max_length=20, null=True)
    grade = models.PositiveSmallIntegerField(null=True, choices=GRADES)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()   
"""

lecture/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User

class Lecture(models.Model):
    name = models.CharField(max_length=100, null=True)
    number = models.IntegerField(null=True)
    fresh_suguni = models.IntegerField(null=True)
    fresh_sugang = models.IntegerField(null=True)
    fresh_limit = models.IntegerField(null=True)
    sopho_suguni = models.IntegerField(null=True)
    sopho_sugang = models.IntegerField(null=True)
    sopho_limit = models.IntegerField(null=True)
    junior_suguni = models.IntegerField(null=True)
    junior_sugang = models.IntegerField(null=True)
    junior_limit = models.IntegerField(null=True)
    senior_suguni = models.IntegerField(null=True)
    senior_sugang = models.IntegerField(null=True)
    senior_limit = models.IntegerField(null=True)

    def __str__(self):
        return str(self.name)
       

accounts/forms.py
from django.contrib.auth.models import User
from django import forms
from accounts.models import Profile
from django.contrib.auth.forms import (UserCreationForm, UserChangeForm, AuthenticationForm)


class RegisterForm(forms.ModelForm):
    password = forms.CharField(label='password', widget=forms.PasswordInput)
    re_password = forms.CharField(label='re_password', widget=forms.PasswordInput)

    class Meta:
        model = Profile
        fields = ['username', 'first_name', 'last_name', 'major', 'grade', 'email', 'nickname']

    def clean_re_password(self):
        cd = self.cleaned_data
        if cd['password'] != cd['re_password']:
            raise forms.ValidationError('비밀번호가 일치하지 않습니다.')

        return cd['re_password']
"""
class ProfileCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Profile
        fields = ('first_name', 'last_name', 'username', 'email', 'nickname', 'major', 'grade')

class LoginForm(AuthenticationForm):
    username = forms.CharField()
    password = forms.CharField()
"""

"""
class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'password']

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['nickname', 'major', 'major_one', 'major_two', 'grade']
"""

accounts/views.py
from pyexpat.errors import messages
from django.contrib import auth
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.db import transaction
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
#from accounts.forms import UserForm, ProfileForm
from accounts.models import Profile
from django.urls import reverse_lazy, reverse
from django.views import generic
from .forms import RegisterForm
"""
class SignUp(generic.CreateView):
    form_class = ProfileCreationForm
    success_url = '/'
    template_name = 'accounts/signup.html'
"""

def signup(request):
    if request.method == 'POST':
        user_form = RegisterForm(request.POST)
        if user_form.is_valid():
            user = user_form.save(commit = False)
            user.set_password(user_form.cleaned_data['password'])
            user.save()
            return render(request, 'accounts/login.html', {'user': user})

            #authenticated_user = authenticate(username=new_user.username,
            #                                  password=request.POST['password1'])
            #auth.login(request, authenticated_user)
            #return HttpResponseRedirect(reverse('login'))
            #return redirect('accounts:login')
    elif request.method == 'GET':
        user_form = RegisterForm()
    return render(request, 'accounts/signup.html', {'user_form': user_form})


def log_in(request):
    if request.method == 'POST':
        login_form = AuthenticationForm(request, request.POST)
        if login_form.is_valid():
            auth.login(request, request.user)
            return redirect(' ')
    else:
        login_form = AuthenticationForm()
        return render(request, 'accounts/login.html', {'login_form': login_form})

    """
            username = login_form.cleaned_data.get('username')
            password = login_form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                print(user)
                auth.login(request, user)
                return redirect('/')
        else:
            # If there were errors, we render the form with these
            # errors
            return render(request, 'accounts/login.html', {'login_form': login_form})

    """

def logout(request):
    auth.logout(request)
    return redirect('posts:list')

"""
def signup(request):
    if request.method == "POST":
        if request.POST["password1"] == request.POST["password2"]:
            user = User.objects.create_user(
                username=request.POST["username"],
                password=request.POST["password1"])
            nickname = request.POST["nickname"]
            profile = Profile(user=user, nickname=nickname)
            profile.save()
            auth.login(request,user)
            return redirect('accounts:login')
    return render(request, 'accounts/signup.html')
"""
"""
@login_required
@transaction.atomic

def signup(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('accounts:login')
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'accounts/signup.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })
"""

def loginmain(request):
    return render(request, 'account/login_main.html')

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<style>
#konkuk{
    position: absolute;
    width: 160px;
    height: 57px;
    left: 50px;
    top: 28px;
}
#copyright{
    position: absolute;
    width: 396px;
    height: 18px;
    left: 746px;
    top: 800px;
    font-family: Noto Sans KR;
    font-style: normal;
    font-weight: 300;
    font-size: 14px;
    line-height: 20px;
    color: #8C8C8C;
}
#logo{
    position: absolute;
    width: 397px;
    height: 130px;
    left: 745px;
    top: 150px;
}
.input_email{
    position: absolute;
    width: 574px;
    height: 67px;
    left: 657px;
    top: 370px;
    background: #FFFFFF;
    border: 1px solid #A7C92C;
    box-sizing: border-box;
    border-radius: 27px;
    font-family: Noto Sans KR;
    font-style: normal;
    font-weight: 500;
    font-size: 18px;
    line-height: 26px;
    text-align: center;
    color: #A4A4A4;
}
.input_pwd{
    position: absolute;
    width: 574px;
    height: 67px;
    left: 657px;
    top: 460px;
    background: #FFFFFF;
    border: 1px solid #A7C92C;
    box-sizing: border-box;
    border-radius: 27px;font-family: Noto Sans KR;
    font-style: normal;
    font-weight: 500;
    font-size: 18px;
    line-height: 26px;
    text-align: center;
    color: #A4A4A4;
}
.btn_login{
    position: absolute;
    width: 574px;
    height: 73px;
    left: 657px;
    top: 620px;
    background: #005128;
    box-shadow: 0px 6px 11px 2px rgba(0, 81, 40, 0.4);
    border-radius: 27px;
    font-family: Noto Sans KR;
    font-style: normal;
    font-weight: normal;
    font-size: 18px;
    line-height: 26px;
    /* identical to box height */
    text-align: center;
    color: #FFFFFF;
}
</style>
<body>
    <img id="logo" src="/static/myku_logo.png">
    <img id="konkuk" src="/static/konkuk.png">
<form method="POST" action="{% url 'accounts:login' %}">
    {% csrf_token %}
    <input type = "hidden" name = "next" value = "">
    <label for="id_email" id="email"></label>
    <input type="text" class="input_email" name="email" placeholder="아이디(학교계정아이디)" maxlength="100" required id="id_email">
    <label for="id_pwd" id="pwd"></label>
    <input type="password" class="input_pwd" name="password" placeholder="비밀번호" maxlength="100" required id="id_pwd">
   <button type = "submit" class="btn_login">로그인</button>
</form>
<div id="copyright">COPYRIGHT 2020 KONKUK UNIVERSITY. ALL RIGHTS RESERVED.</div>
</body>
</html>

accounts/templates/accounts/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<style>
.input_name{
position: absolute;
width: 438px;
height: 67px;
left: 502px;
top: 379px;
background: #FFFFFF;
border: 1px solid #A7C92C;
box-sizing: border-box;
border-radius: 27px;
font-family: Noto Sans KR;
font-style: normal;
font-weight: 500;
font-size: 18px;
line-height: 26px;
color: #A4A4A4;
text-align: center;}

.input_nickname{
position: absolute;
width: 438px;
height: 67px;
left: 979px;
top: 379px;
background: #FFFFFF;
border: 1px solid #A7C92C;
box-sizing: border-box;
border-radius: 27px;
font-family: Noto Sans KR;
font-style: normal;
font-weight: 500;
font-size: 18px;
line-height: 26px;
text-align: center;
color: #A4A4A4;}

.input_email{
position: absolute;
width: 438px;
height: 67px;
left: 502px;
top: 466px;
background: #FFFFFF;
border: 1px solid #A7C92C;
box-sizing: border-box;
border-radius: 27px;
font-family: Noto Sans KR;
font-style: normal;
font-weight: 500;
font-size: 18px;
line-height: 26px;
text-align: center;
color: #A4A4A4;
}
.input_major{
position: absolute;
width: 438px;
height: 67px;
left: 979px;
top: 466px;
background: #FFFFFF;
border: 1px solid #A7C92C;
box-sizing: border-box;
border-radius: 27px;
font-family: Noto Sans KR;
font-style: normal;
font-weight: 500;
font-size: 18px;
line-height: 26px;
text-align: center;
color: #A4A4A4;
}
.input_pwd{
position: absolute;
width: 438px;
height: 67px;
left: 502px;
top: 553px;
background: #FFFFFF;
border: 1px solid #A7C92C;
box-sizing: border-box;
border-radius: 27px;
font-family: Noto Sans KR;
font-style: normal;
font-weight: 500;
font-size: 18px;
line-height: 26px;
text-align: center;
color: #A4A4A4;
}
.input_grade{
position: absolute;
width: 438px;
height: 67px;
left: 979px;
top: 553px;
background: #FFFFFF;
border: 1px solid #A7C92C;
box-sizing: border-box;
border-radius: 27px;
font-family: Noto Sans KR;
font-style: normal;
font-weight: 500;
font-size: 18px;
line-height: 26px;
text-align: center;
color: #A4A4A4;
}
.intro_signup{
position: absolute;
width: 200px;
height: 70px;
left: 872px;
top: 239px;
font-family: Noto Sans KR;
font-style: normal;
font-weight: 300;
font-size: 48px;
line-height: 70px;
/* identical to box height */
color: #727272;
}
.btn_signup{
position: absolute;
width: 915px;
height: 73px;
left: 502px;
top: 757px;
background: #A7C92C;
box-shadow: 0px 6px 11px 2px rgba(167, 201, 44, 0.4);
border-radius: 27px;
font-family: Noto Sans KR;
font-style: normal;
font-weight: normal;
font-size: 18px;
line-height: 26px;
/* identical to box height */
color: #FFFFFF;
border:0;
outline:0;
}
#logo{
position: absolute;
    width: 250px;
    height: 80px;
    left: 1650px;
    top: 0px;
}
#konkuk{
    position: absolute;
    width: 160px;
    height: 57px;
    left: 50px;
    top: 28px;
}
</style>
<body>
<div class="row">
    <div class="col"></div>
    <div class="'col-6">
        <img id="logo" src="/static/myku_logo.png">
        <img id="konkuk" src="/static/konkuk.png">
        <div class="intro_signup" role="alert">
            회원가입</div>
        <form id="form_signup" action="" method="post">
            {% csrf_token %}
            <!--{{ user_form.as_p }}-->
            <p>
                <label for="id_name" id="name"></label>
                <input type="text" class="input_name" name="lastname" placeholder="이름" maxlength="100" required id="id_name">
            </p>
             <p>
                <label for="id_nickname" id="nickname"></label>
                <input type="text" class="input_nickname" name="nickname" placeholder="닉네임" maxlength="100" required id="id_nickname">
            </p>
            <p>
                <label for="id_email" id="email"></label>
                <input type="text" class="input_email" name="email" placeholder="아이디(학교 계정 아이디)" maxlength="100" required id="id_email">
            </p>
            <p>
                <label for="id_major" id="major"></label>
                <input type="text" class="input_major" name="major" placeholder="학과정보(선택)" maxlength="100" required id="id_major">
            </p>
            <p>
                <label for="id_pwd" id="pwd"></label>
                <input type="password" class="input_pwd" name="password" placeholder="비밀번호" maxlength="100" required id="id_pwd">
            </p>
            <p>
                <select name="grade" size="1" form="form_signup" class="input_grade">
                    학년정보필수
                    <option value="1학년">1학년</option>
                    <option value="2학년">2학년</option>
                    <option value="3학년">3학년</option>
                    <option value="4학년">4학년</option>
                </select>

            </p>

            <!--{{ user_form.as_p }}
            {{ profile_form.as_p }}-->
            <input type="submit" value="가입하기" class = 'btn_signup'>
        </form>
    </div>
    <div class="col"></div>

</div>
</body>
</html>