accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.log_in, name='login'),
    path('logout/', LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('loginmain/', views.loginmain, name='loginmain'),
]

main/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index ,name='first'),
    path('loginmain/', views.loginmain ,name='loginmain'),
]

myku/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    #path('accounts/', include('django.contrib.auth.urls')),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'main/main.html')


def loginmain(request):
    return render(request, 'main/login_main.html')

main/templates/main/login_main.html
{% extends 'base.html'%}
{% block content %}
<style>

.wrapper{
  width : 100%;
  margin: 200px 15%;
  display: grid;
  grid-template-columns: 1fr 1fr 1fr;

}
.circle{
  display : inline-block;
  width : 150px;
  height: 150px;
  border-radius : 50%;
  background: #FFFFFF;
  box-shadow: 3px 4px 18px 2px rgba(167, 201, 44, 0.25);
  transform: matrix(1, 0, 0, -1, 0, 0);
  text-align : center;
}
.title{
  width : 200px;
font-family: Noto Sans KR;
font-style: normal;
font-weight: 300;
font-size: 22px;
line-height: 52px;
color: #000000;
text-align : center;
}
.menu{
position: absolute;
left: 35%;
right: 30%;
top: 40%;
bottom: -55%;
transform: matrix(1, 0, 0, -1, 0, 0);
}

</style>


<div class="wrapper">

  <div class="sector">
    <div class="title">나의 강의</div>
    <div class="circle">
      <img class="menu" src="/static/Vector (1).png">
    </div>
  </div>
  <div class="sector">
  <div class="title">수강인원 현황 조회 </div>
    <div class="circle">
      <img class="menu" src="/static/Vector (2).png">
    </div>
  </div>  
  <div class="sector">
  <div class="title">커뮤니티</div>
    <div class="circle">
      <img class="menu" src="/static/Vector (3).png">
    </div>
  </div>

</div>
{% endblock %}

main/templates/main/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>내 한학기를 KU해줘</title>
</head>
<style>
#logo{
    position: absolute;
    width: 397px;
    height: 140px;
    left: 745px;
    top: 262px;
}
#konkuk{
    position: absolute;
    width: 160px;
    height: 57px;
    left: 50px;
    top: 28px;
}
#left_green{
    position: absolute;
    width: 85px;
    height: 50px;
    left: 504px;
    top: 0px;
}
#right_green{
    position: absolute;
    width: 200px;
    height: 80px;
    left: 1255px;
    top: 0px;
}
#bottom_green{
    position: absolute;
    width: 200px;
    height: 60px;
    left: 200px;
    top: 800px;
}
#btn_signup{
    position: absolute;
    width: 300px;
    height: 73px;
    left: 633px;
    top: 500px;
    background: #A7C92C;
    box-shadow: 0px 6px 11px 2px rgba(167, 201, 44, 0.4);
    border-radius: 27px;
    border: 0;
    outline: 0;
    font-family: Noto Sans KR;
    font-style: normal;
    font-weight: normal;
    font-size: 18px;
    line-height: 26px;
    /* identical to box height */
    color: #FFFFFF;
}
#btn_login{
    position: absolute;
    width: 300px;
    height: 73px;
    left: 955px;
    top: 500px;
    background: #005128;
    box-shadow: 0px 6px 11px 2px rgba(0, 81, 40, 0.4);
    border-radius: 27px;
    border: 0;
    outline: 0;
    font-family: Noto Sans KR;
    font-style: normal;
    font-weight: normal;
    font-size: 18px;
    line-height: 26px;
    /* identical to box height */
    color: #FFFFFF;
}
#copyright{
    position: absolute;
    width: 396px;
    height: 18px;
    left: 746px;
    top: 800p;
    font-family: Noto Sans KR;
    font-style: normal;
    font-weight: 300;
    font-size: 14px;
    line-height: 20px;
    color: #8C8C8C;
}
</style>
<body>
    <img id="logo" src="/static/myku_logo.png">
    <img id="konkuk" src="/static/konkuk.png">
    <img id="left_green" src="/static/green_top.png">
    <img id="right_green" src="/static/green_top.png">
    <img id="bottom_green" src="/static/deep_down.png">
    <div id="btn">
            <button type="button" id="btn_signup" onclick="location.href='{% url 'accounts:signup' %}'">
               회원가입</button>
            <button type="button" id="btn_login" onclick="location.href='{% url 'accounts:login' %}'">
                로그인</button>
    </div>
    <div id="copyright">COPYRIGHT 2020 KONKUK UNIVERSITY. ALL RIGHTS RESERVED.</div>
    <!--
    {% if user.is_authenticated %}
    <div>{{user.username}} 환영합니다.</div>
    {% endif %}-->
</body>
</html>